Do all dependabot updates and fix issues
hivtools/hint pull request #999
Opened 2024-09-13 16:41 UTC by r-ash

## Description

This PR does all currently open dependabot updates, and fixes up any issues introduced from them
* #938 
* #979 
* #986 

## Type of version change

None

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2024-09-13 17:15 UTC, r-ash commented on src/app/static/src/tests/e2e/reviewInput.spec.ts
> +    await expect(page.locator("#review-inputs")).toHaveScreenshot("time-series-anc.png")
I think this will be a little less flaky version I hope!

2024-09-16 12:35 UTC, M-Kusumgar requested changes
this looks good, btw just spotted something weird in the table, which is not there in mrc-4856, in the table plot:
1. deselect both in sex filter
2. select both again

in this version its a bit weird, in the old version the table just filled the entire space, i think we mightve missed something in the table component

2024-09-16 13:05 UTC, M-Kusumgar commented on src/app/static/src/app/components/plots/table/TableDisplay.vue
>      // suppressMenu hides the filter menu which showed on the column title
also just spotted this 
```suggestion
    // suppressHeaderMenuButton hides the filter menu which showed on the column title
```

2024-09-16 13:09 UTC, M-Kusumgar approved these changes
Niceeeee

2024-09-16 13:10 UTC, merged